### ISSUE TITLE
PostCSS issue when trying to preview example-site

### ISSUE THREAD

**Issue by dmodena** [jacksalici/salinger-theme#3]
I'm having issues trying to preview the example site locally using this theme. When I follow the instructions from the readme file, I get the following error:

<img width="682" alt="Screenshot 2023-08-21 at 08 27 12" src="https://github.com/jacksalici/salinger-theme/assets/11446011/ffee6804-88fd-4673-9365-d9a841d55364">

**Local configuration**

I have a brand new Hugo install, running in MacOS, which I performed by following the instructions from the [Hugo website](https://gohugo.io/installation/macos/), running on an M1 Macbook with the following configuration:

MacOS version: Ventura 13.5
Go version: go1.21.0 darwin/arm64
Git version: 2.40.0
Sass version: 1.65.1 compiled with dart2js 3.0.7

**Possible solution**

I don't have PostCSS installed globally, since it was not required to install Hugo itself. If this is needed to preview the example-site, I think it should be added as a requirement in the docs. But I believe a better approach would be to have it automatically installed as a local dependency, if possible (just like we do with npm packages after running `npm install`).

**Comment by jacksalici** [comment]
Hello, thank you for pointing this out to me. I will look for it deeply. Actually I am not a PostCSS expert so I may have misunderstood some instructions...

**Comment by jacksalici** [comment]
Could you please check if the example-site works after having installed the dependencies in the main folder? 
The setup script would become:

```bash
git clone https://github.com/jacksalici/salinger-theme.git salinger
cd salinger/
npm install
cd example-site
hugo server -t ../..

```

TYSM

**Comment by brykzahmz** [comment]
I had similar issues this morning and believe it was due to _hugo mod npm pack_ not working correctly. Installing the dependencies manually via npm got me to a working state.

**Comment by dmodena** [comment]
> ```shell
> git clone https://github.com/jacksalici/salinger-theme.git salinger
> ```

Yes, this works perfectly! Thank you! I believe this issue can be closed now.

**Comment by dmodena** [comment]
> Could you please check if the example-site works after having installed the dependencies in the main folder? The setup script would become:
> 
> ```shell
> git clone https://github.com/jacksalici/salinger-theme.git salinger
> cd salinger/
> npm install
> cd example-site
> hugo server -t ../..
> ```
> 
> TYSM

Yes, this worked perfectly! Thank you! I believe this issue can be closed now.

**Comment by jacksalici** [comment]
> I had similar issues this morning and believe it was due to _hugo mod npm pack_ not working correctly. Installing the dependencies manually via npm got me to a working state.

@brykzahmz with the last commit, I have just added a more comprehensive setup documentation that **should** solve also your problem. Otherwise, please open a new issue and I will be glad to investigate further.

> Yes, this worked perfectly! Thank you! I believe this issue can be closed now.

@dmodena my pleasure. TY.
