### ISSUE TITLE
daisui themes

### ISSUE THREAD

**Issue by till** [jacksalici/salinger-theme#6]
Hey 👋🏼 ,

thanks for creating this. :) 

I was wondering if it's possible to use the theming in daisyui with your theme.
https://daisyui.com/docs/themes/

The theming in daisyui lets one pick a color scheme and fonts, etc..

Cheers

**Comment by till** [comment]
I guess I figured part of it out. You created your own themes and these are loaded only?

**Comment by jacksalici** [comment]
Hi Till, thank you for using Salinger, and sorry for the late answer.

> I was wondering if it's possible to use the theming in DaisyUI with your theme.
> https://daisyui.com/docs/themes/

The answer is yes but with a few limitations. There is indeed support for DaisyUI theming but as of now, it is only possible to switch between a light ("lit") and a dark ("dim") theme, which can be customizable from the `tailwind.config.js`. As you can see, they are currently inheriting everything from two of the standard themes but they can also be [customized further](https://daisyui.com/docs/themes/#-4). Unfortunately, it's not possible to edit them from the `hugo.toml` file, at least for now... Regarding the fonts, they can also be changed in the same file but the import in the CSS might be arranged consequently. 

```js
themes: [
      {
        lit: {
          ...require("daisyui/src/theming/themes")["[data-theme=corporate]"],
        },
      },
      {
        dim: {
          ...require("daisyui/src/theming/themes")["[data-theme=business]"],
        },
      },
```

I also have noticed that the demo link in the readme points to my website which not uses this theme anymore. I apologize for the confusion and I will change it as soon as possible...

**Comment by till** [comment]
Thank you, this was helpful!
